// Static game data: attributes, positions, formations, roles, traits, nations, leagues and calendar rules.
// Clubs are in clubs.js.
(function () {
  const FM = window.FM;

  FM.D = {};

  // ---------- Attributes (1–20 scale, FM-style) ----------
  FM.D.ATTRS = [
    'pace',
    'stamina',
    'strength',
    'dribbling',
    'technique',
    'passing',
    'vision',
    'finishing',
    'tackling',
    'positioning',
    'composure',
    'workRate',
    'reflexes',
    'handling',
  ];
  FM.D.ATTR_LABEL = {
    pace: 'Pace',
    stamina: 'Stamina',
    strength: 'Strength',
    dribbling: 'Dribbling',
    technique: 'Technique',
    passing: 'Passing',
    vision: 'Vision',
    finishing: 'Finishing',
    tackling: 'Tackling',
    positioning: 'Positioning',
    composure: 'Composure',
    workRate: 'Work Rate',
    reflexes: 'Reflexes',
    handling: 'Handling',
  };
  FM.D.ATTR_GROUPS = {
    Physical: ['pace', 'stamina', 'strength', 'workRate'],
    Technical: ['dribbling', 'technique', 'passing', 'finishing', 'tackling'],
    Mental: ['vision', 'positioning', 'composure'],
    Goalkeeping: ['reflexes', 'handling'],
  };
  // Radar axes: label -> attrs averaged
  FM.D.RADAR = {
    Pace: ['pace'],
    Attack: ['finishing', 'composure'],
    Creativity: ['vision', 'passing'],
    Skill: ['dribbling', 'technique'],
    Defence: ['tackling', 'positioning'],
    Physical: ['strength', 'stamina', 'workRate'],
  };
  FM.D.RADAR_GK = {
    Reflexes: ['reflexes'],
    Handling: ['handling'],
    Positioning: ['positioning'],
    Distribution: ['passing'],
    Composure: ['composure'],
    Physical: ['strength', 'pace'],
  };

  // Scouting language: [elite >=17, good >=14, weak <=7]
  FM.D.PHRASES = {
    pace: ['Blistering acceleration', 'Quick across the ground', 'Lacks a yard of pace'],
    stamina: ['Tireless — runs all day', 'Good engine', 'Fades late in games'],
    strength: ['Built like a tank', 'Holds his own physically', 'Easily knocked off the ball'],
    dribbling: ['Beats players for fun', 'Comfortable running with the ball', 'Loses the ball under pressure'],
    technique: ['Silky first touch', 'Clean technique', 'Heavy touch'],
    passing: ['Pinpoint range of passing', 'Tidy, reliable passer', 'Wasteful in possession'],
    vision: ["Sees passes others don't", 'Good awareness of teammates', 'Rarely lifts his head'],
    finishing: ['Ruthless in front of goal', 'Knows where the net is', 'Snatches at chances'],
    tackling: ['Ferocious, perfectly timed tackles', 'Wins his duels', 'Rash in the challenge'],
    positioning: ['Reads the game superbly', 'Disciplined positionally', 'Often caught out of position'],
    composure: ['Ice in his veins', 'Calm on the ball', 'Panics under pressure'],
    workRate: ['Relentless presser', 'Puts a shift in', 'Coasts through games'],
    reflexes: ['Cat-like reflexes', 'Sharp shot-stopper', 'Slow to react'],
    handling: ['Safe hands', 'Dependable handling', 'Spills routine shots'],
  };

  // ---------- Positions ----------
  FM.D.POS = ['GK', 'CB', 'FB', 'DM', 'CM', 'AM', 'W', 'ST'];
  FM.D.POS_NAME = {
    GK: 'Goalkeeper',
    CB: 'Centre-Back',
    FB: 'Full-Back',
    DM: 'Defensive Mid',
    CM: 'Central Mid',
    AM: 'Attacking Mid',
    W: 'Winger',
    ST: 'Striker',
    WB: 'Wing-Back',
  };
  FM.D.POS_GROUP = { GK: 'GK', CB: 'DEF', FB: 'DEF', DM: 'MID', CM: 'MID', AM: 'MID', W: 'ATT', ST: 'ATT' };
  // Weights used to compute current ability (CA) per position
  FM.D.POS_W = {
    GK: { reflexes: 3, handling: 3, positioning: 1.5, composure: 1, passing: 0.5 },
    CB: { tackling: 3, positioning: 3, strength: 2, pace: 1, composure: 1, passing: 0.5 },
    FB: { pace: 2, tackling: 2, positioning: 1.5, stamina: 1.5, workRate: 1, passing: 1, dribbling: 0.5 },
    DM: { tackling: 2.5, positioning: 2, passing: 2, workRate: 1.5, stamina: 1, strength: 1, vision: 0.5 },
    CM: { passing: 2.5, vision: 2, technique: 1.5, stamina: 1.5, workRate: 1, tackling: 0.7, composure: 1 },
    AM: { vision: 2.5, technique: 2.5, passing: 2, dribbling: 2, finishing: 1, composure: 1 },
    W: { pace: 2.5, dribbling: 2.5, technique: 1.5, passing: 1, finishing: 1, stamina: 1 },
    ST: { finishing: 3, composure: 2, pace: 1.5, strength: 1, technique: 1, dribbling: 1, positioning: 0.5 },
  };
  // How well a natural position fits a formation slot type (0–1)
  FM.D.FIT = {
    GK: { GK: 1 },
    CB: { CB: 1, DM: 0.75, FB: 0.7 },
    FB: { FB: 1, WB: 0.95, CB: 0.7, W: 0.65, DM: 0.6 },
    DM: { DM: 1, CM: 0.9, CB: 0.75 },
    CM: { CM: 1, DM: 0.85, AM: 0.85, WB: 0.55 },
    AM: { AM: 1, CM: 0.85, W: 0.8, ST: 0.75 },
    W: { W: 1, AM: 0.8, WB: 0.75, ST: 0.7, FB: 0.55 },
    ST: { ST: 1, AM: 0.75, W: 0.7 },
  };

  // ---------- Formations (x: 0 own goal → 1 opponent goal, y: 0 left → 1 right) ----------
  const GK = { t: 'GK', x: 0.04, y: 0.5 };
  FM.D.FORMATIONS = {
    '4-3-3': [
      GK,
      { t: 'FB', x: 0.24, y: 0.14 },
      { t: 'CB', x: 0.2, y: 0.38 },
      { t: 'CB', x: 0.2, y: 0.62 },
      { t: 'FB', x: 0.24, y: 0.86 },
      { t: 'DM', x: 0.38, y: 0.5 },
      { t: 'CM', x: 0.5, y: 0.3 },
      { t: 'CM', x: 0.5, y: 0.7 },
      { t: 'W', x: 0.7, y: 0.14 },
      { t: 'ST', x: 0.76, y: 0.5 },
      { t: 'W', x: 0.7, y: 0.86 },
    ],
    '4-2-3-1': [
      GK,
      { t: 'FB', x: 0.24, y: 0.14 },
      { t: 'CB', x: 0.2, y: 0.38 },
      { t: 'CB', x: 0.2, y: 0.62 },
      { t: 'FB', x: 0.24, y: 0.86 },
      { t: 'DM', x: 0.38, y: 0.38 },
      { t: 'DM', x: 0.38, y: 0.62 },
      { t: 'W', x: 0.62, y: 0.15 },
      { t: 'AM', x: 0.6, y: 0.5 },
      { t: 'W', x: 0.62, y: 0.85 },
      { t: 'ST', x: 0.78, y: 0.5 },
    ],
    '4-4-2': [
      GK,
      { t: 'FB', x: 0.24, y: 0.14 },
      { t: 'CB', x: 0.2, y: 0.38 },
      { t: 'CB', x: 0.2, y: 0.62 },
      { t: 'FB', x: 0.24, y: 0.86 },
      { t: 'W', x: 0.5, y: 0.13 },
      { t: 'CM', x: 0.45, y: 0.38 },
      { t: 'CM', x: 0.45, y: 0.62 },
      { t: 'W', x: 0.5, y: 0.87 },
      { t: 'ST', x: 0.74, y: 0.4 },
      { t: 'ST', x: 0.74, y: 0.6 },
    ],
    '3-5-2': [
      GK,
      { t: 'CB', x: 0.2, y: 0.27 },
      { t: 'CB', x: 0.17, y: 0.5 },
      { t: 'CB', x: 0.2, y: 0.73 },
      { t: 'WB', x: 0.44, y: 0.09 },
      { t: 'DM', x: 0.36, y: 0.5 },
      { t: 'CM', x: 0.5, y: 0.32 },
      { t: 'CM', x: 0.5, y: 0.68 },
      { t: 'WB', x: 0.44, y: 0.91 },
      { t: 'ST', x: 0.75, y: 0.4 },
      { t: 'ST', x: 0.75, y: 0.6 },
    ],
    '3-4-3': [
      GK,
      { t: 'CB', x: 0.2, y: 0.27 },
      { t: 'CB', x: 0.17, y: 0.5 },
      { t: 'CB', x: 0.2, y: 0.73 },
      { t: 'WB', x: 0.46, y: 0.09 },
      { t: 'CM', x: 0.44, y: 0.38 },
      { t: 'CM', x: 0.44, y: 0.62 },
      { t: 'WB', x: 0.46, y: 0.91 },
      { t: 'W', x: 0.7, y: 0.18 },
      { t: 'ST', x: 0.77, y: 0.5 },
      { t: 'W', x: 0.7, y: 0.82 },
    ],
    '5-3-2': [
      GK,
      { t: 'WB', x: 0.3, y: 0.08 },
      { t: 'CB', x: 0.19, y: 0.3 },
      { t: 'CB', x: 0.16, y: 0.5 },
      { t: 'CB', x: 0.19, y: 0.7 },
      { t: 'WB', x: 0.3, y: 0.92 },
      { t: 'CM', x: 0.44, y: 0.3 },
      { t: 'DM', x: 0.4, y: 0.5 },
      { t: 'CM', x: 0.44, y: 0.7 },
      { t: 'ST', x: 0.7, y: 0.4 },
      { t: 'ST', x: 0.7, y: 0.6 },
    ],
  };
  FM.D.shapeOf = (f) => ({ 3: 'Back 3', 4: 'Back 4', 5: 'Back 5' })[f[0]];

  // Roles: engine modifiers (att/mid/def) + positional nudges in possession (dx, dy toward centre if 'in')
  FM.D.ROLES = {
    GK: { Goalkeeper: {}, 'Sweeper Keeper': { mid: 0.02, dx: 0.06, risk: 0.01 } },
    CB: {
      'Centre-Back': { def: 0.02 },
      'Ball-Playing CB': { mid: 0.02, def: -0.01 },
      Libero: { mid: 0.03, def: -0.02, dx: 0.12 },
    },
    FB: {
      'Full-Back': { def: 0.02 },
      'Wing-Back': { att: 0.02, def: -0.01, dx: 0.14 },
      'Inverted FB': { mid: 0.03, dx: 0.12, in: 0.28 },
    },
    WB: { 'Wing-Back': { att: 0.02 }, 'Complete WB': { att: 0.03, def: -0.02, dx: 0.1 } },
    DM: {
      Anchor: { def: 0.03, att: -0.01 },
      'Deep-Lying Playmaker': { mid: 0.03 },
      'Segundo Volante': { att: 0.03, def: -0.01, dx: 0.14 },
    },
    CM: {
      'Box-to-Box': { att: 0.01, def: 0.01, mid: 0.01 },
      Carrilero: { def: 0.02, mid: 0.01, in: -0.1 },
      Mezzala: { att: 0.03, def: -0.01, dx: 0.1, in: -0.12 },
      Playmaker: { mid: 0.03 },
    },
    AM: {
      'Advanced Playmaker': { mid: 0.03 },
      Trequartista: { att: 0.03, def: -0.02 },
      'Shadow Striker': { att: 0.03, dx: 0.1 },
    },
    W: {
      Winger: { att: 0.02, cross: 0.1 },
      'Inverted Winger': { att: 0.02, mid: 0.01, in: 0.2 },
      'Inside Forward': { att: 0.03, in: 0.25, dx: 0.06 },
    },
    ST: {
      Poacher: { att: 0.03, dx: 0.04 },
      'Target Man': { att: 0.02, cross: 0.1 },
      'False 9': { mid: 0.04, att: 0.01, dx: -0.14 },
      'Pressing Forward': { att: 0.01, press: 0.05 },
    },
  };

  FM.D.BUILDUP = ['Short', 'Direct', 'Counter', 'Possession'];
  FM.D.PRESS = ['High Press', 'Mid Block', 'Low Block'];

  // ---------- Traits ----------
  FM.D.TRAITS = {
    'Big Game Player': { icon: '⭐', desc: 'Raises his level in derbies and against top sides.' },
    'Injury Prone': { icon: '🩹', desc: 'Picks up knocks more often than most.' },
    'Late Bloomer': { icon: '🌱', desc: 'Keeps improving well into his mid-twenties.' },
    Loyal: { icon: '💙', desc: 'Committed to the club. Ignores outside interest.' },
    Mercenary: { icon: '💰', desc: 'Follows the money. Unsettled by bigger offers.' },
    Leader: { icon: '🎖️', desc: 'Organises and lifts teammates. Natural captain.' },
    'Media Friendly': { icon: '🎙️', desc: 'Handles the press brilliantly. Fans love him.' },
    Temperamental: { icon: '🔥', desc: 'Volatile. More cards, bigger mood swings.' },
    'Derby Specialist': { icon: '⚔️', desc: 'Lives for the derby.' },
    'Fair-Weather': { icon: '🌧️', desc: 'Hates rainy matches. Noticeably worse in the wet.' },
    Consistent: { icon: '📈', desc: 'Rarely has a bad game.' },
    Flair: { icon: '✨', desc: 'Tries the unexpected. Moments of magic.' },
  };

  // ---------- Nations ----------
  FM.D.NATIONS = {
    ENG: {
      name: 'England',
      flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
      region: 'ENG',
      style: 'Hard-working and physical',
      bias: { workRate: 2, strength: 1.5, stamina: 1 },
      fn: [
        'Jack',
        'Harry',
        'Oliver',
        'George',
        'Charlie',
        'Tom',
        'James',
        'Ben',
        'Callum',
        'Kieran',
        'Luke',
        'Ryan',
        'Jordan',
        'Mason',
        'Declan',
        'Jamie',
        'Aaron',
        'Connor',
        'Reece',
        'Lewis',
        'Dan',
        'Sam',
        'Nathan',
        'Joe',
        'Alfie',
        'Archie',
        'Kyle',
        'Marcus',
        'Ollie',
        'Ethan',
        'Tyler',
        'Rhys',
      ],
      ln: [
        'Walker',
        'Hughes',
        'Barnes',
        'Clarke',
        'Wright',
        'Turner',
        'Mitchell',
        'Cooper',
        'Ward',
        'Morris',
        'Bennett',
        'Price',
        'Fletcher',
        'Holloway',
        'Palmer',
        'Shaw',
        'Webb',
        'Gray',
        'Doyle',
        'Harding',
        'Rowe',
        'Pritchard',
        'Sutton',
        'Hale',
        'Kemp',
        'Lowe',
        'Marsh',
        'Bishop',
        'Carver',
        'Dunn',
        'Fox',
        'Goodwin',
        'Heath',
        'Knox',
        'Lambert',
        'Osei',
        'Adeyemi',
        'Campbell',
      ],
    },
    BRA: {
      name: 'Brazil',
      flag: '🇧🇷',
      region: 'SAM',
      style: 'Flair and technique',
      bias: { dribbling: 2.5, technique: 2, finishing: 1 },
      fn: [
        'Lucas',
        'Gabriel',
        'Matheus',
        'João',
        'Pedro',
        'Rafael',
        'Thiago',
        'Vinícius',
        'Caio',
        'Diego',
        'Felipe',
        'Bruno',
        'Igor',
        'Wesley',
        'Everton',
        'Rodrigo',
      ],
      ln: [
        'Silva',
        'Santos',
        'Oliveira',
        'Souza',
        'Lima',
        'Pereira',
        'Costa',
        'Ferreira',
        'Almeida',
        'Carvalho',
        'Ribeiro',
        'Gomes',
        'Barbosa',
        'Rocha',
        'Nascimento',
        'Moura',
      ],
    },
    ARG: {
      name: 'Argentina',
      flag: '🇦🇷',
      region: 'SAM',
      style: 'Street-smart competitors',
      bias: { dribbling: 1.5, vision: 1.5, composure: 1.5, tackling: 1 },
      fn: [
        'Santiago',
        'Matías',
        'Nicolás',
        'Facundo',
        'Lautaro',
        'Julián',
        'Agustín',
        'Franco',
        'Gonzalo',
        'Tomás',
        'Emiliano',
        'Valentín',
      ],
      ln: [
        'González',
        'Rodríguez',
        'Fernández',
        'López',
        'Martínez',
        'Díaz',
        'Romero',
        'Sosa',
        'Álvarez',
        'Acosta',
        'Benítez',
        'Medina',
        'Herrera',
        'Correa',
      ],
    },
    JPN: {
      name: 'Japan',
      flag: '🇯🇵',
      region: 'ASIA',
      style: 'Disciplined technicians',
      bias: { technique: 2, passing: 2, workRate: 2, strength: -1.5 },
      fn: [
        'Haruto',
        'Sota',
        'Yuto',
        'Ren',
        'Kaito',
        'Daiki',
        'Takumi',
        'Shota',
        'Ryo',
        'Kenta',
        'Hiroki',
        'Yuki',
        'Sho',
        'Kaoru',
      ],
      ln: [
        'Tanaka',
        'Suzuki',
        'Takahashi',
        'Watanabe',
        'Ito',
        'Yamamoto',
        'Nakamura',
        'Kobayashi',
        'Kato',
        'Yoshida',
        'Yamada',
        'Sasaki',
        'Matsumoto',
        'Inoue',
        'Kimura',
        'Endo',
      ],
    },
    KOR: {
      name: 'South Korea',
      flag: '🇰🇷',
      region: 'ASIA',
      style: 'Relentless engines',
      bias: { stamina: 2.5, workRate: 2.5, pace: 1 },
      fn: [
        'Ji-ho',
        'Seung-woo',
        'Hyun-jun',
        'Jae-won',
        'Do-yeon',
        'Tae-hyun',
        'Joon-ho',
        'Woo-jin',
        'Sang-hoon',
        'Dong-hyun',
      ],
      ln: ['Kim', 'Lee', 'Park', 'Choi', 'Jung', 'Kang', 'Cho', 'Yoon', 'Jang', 'Lim', 'Han', 'Oh'],
    },
    THA: {
      name: 'Thailand',
      flag: '🇹🇭',
      region: 'ASIA',
      style: 'Quick, nimble dribblers',
      bias: { pace: 1.5, dribbling: 1.5, technique: 1, strength: -2 },
      fn: [
        'Supachai',
        'Chanathip',
        'Theerathon',
        'Ekanit',
        'Suphanat',
        'Kritsada',
        'Thanawat',
        'Nattapong',
        'Pansa',
        'Weerathep',
        'Sarach',
        'Channarong',
      ],
      ln: [
        'Srisuk',
        'Bunmathan',
        'Songkrasin',
        'Chaiyawong',
        'Kaewprom',
        'Phonrat',
        'Mahawong',
        'Saengchan',
        'Thongdee',
        'Wongsa',
        'Rattanakorn',
        'Inthasen',
      ],
    },
    SRB: {
      name: 'Serbia',
      flag: '🇷🇸',
      region: 'EUR',
      style: 'Tough, uncompromising defenders',
      bias: { tackling: 2.5, strength: 2, positioning: 1.5 },
      fn: [
        'Nikola',
        'Luka',
        'Stefan',
        'Marko',
        'Aleksandar',
        'Nemanja',
        'Dušan',
        'Filip',
        'Miloš',
        'Uroš',
        'Lazar',
        'Strahinja',
      ],
      ln: [
        'Jovanović',
        'Petrović',
        'Nikolić',
        'Marković',
        'Đorđević',
        'Stojanović',
        'Ilić',
        'Pavlović',
        'Milošević',
        'Stanković',
        'Kostić',
        'Lukić',
      ],
    },
    FRA: {
      name: 'France',
      flag: '🇫🇷',
      region: 'EUR',
      style: 'Elite athletes',
      bias: { pace: 2.5, strength: 2, stamina: 1.5 },
      fn: [
        'Hugo',
        'Théo',
        'Lucas',
        'Mathis',
        'Nathan',
        'Enzo',
        'Maxime',
        'Antoine',
        'Yanis',
        'Rayan',
        'Moussa',
        'Ibrahima',
        'Jules',
        'Clément',
      ],
      ln: [
        'Martin',
        'Bernard',
        'Dubois',
        'Moreau',
        'Laurent',
        'Lefebvre',
        'Fofana',
        'Diallo',
        'Camara',
        'Traoré',
        'Mendy',
        'Girard',
        'Mercier',
        'Blanc',
      ],
    },
    ESP: {
      name: 'Spain',
      flag: '🇪🇸',
      region: 'EUR',
      style: 'Positional play specialists',
      bias: { passing: 2.5, vision: 2, technique: 2, strength: -1 },
      fn: ['Pablo', 'Sergio', 'Álvaro', 'Javier', 'Iker', 'Hugo', 'Adrián', 'Marcos', 'Rubén', 'Dani'],
      ln: [
        'García',
        'Martín',
        'Sánchez',
        'Ruiz',
        'Moreno',
        'Muñoz',
        'Navarro',
        'Torres',
        'Ramos',
        'Gil',
        'Vidal',
        'Serrano',
      ],
    },
    NGA: {
      name: 'Nigeria',
      flag: '🇳🇬',
      region: 'AFR',
      style: 'Explosive athletes',
      bias: { pace: 2.5, strength: 2, dribbling: 1 },
      fn: [
        'Chidi',
        'Emeka',
        'Samuel',
        'Victor',
        'Ahmed',
        'Tunde',
        'Kelechi',
        'Uche',
        'Ifeanyi',
        'Taiwo',
        'Wilfred',
        'Ademola',
      ],
      ln: [
        'Okafor',
        'Adeyemi',
        'Nwosu',
        'Balogun',
        'Eze',
        'Okonkwo',
        'Obi',
        'Adebayo',
        'Chukwu',
        'Ogunleye',
        'Musa',
        'Ndidi',
      ],
    },
  };
  // More nations so league squads look like real leagues (fictional name combinations)
  const addN = (code, name, flag, region, style, bias, fn, ln) =>
    (FM.D.NATIONS[code] = {
      name,
      flag,
      region,
      style,
      bias,
      fn: fn.split(' '),
      ln: ln.split(',').map((x) => x.trim()),
    });
  // Add first names (space-separated) and surnames (comma-separated) to a nation, skipping ones it already has
  FM.D.addNames = (c, fn, ln) => {
    const N = FM.D.NATIONS[c];
    fn.split(' ').forEach((x) => x && !N.fn.includes(x) && N.fn.push(x));
    ln.split(',')
      .map((x) => x.trim())
      .forEach((x) => x && !N.ln.includes(x) && N.ln.push(x));
  };
  addN(
    'POR',
    'Portugal',
    '🇵🇹',
    'EUR',
    'Technical, inventive',
    { dribbling: 1.5, technique: 1.5, passing: 1 },
    'João Diogo Rúben Tiago Gonçalo André Rafael Nuno Vitor Francisco Pedro Hugo',
    'Pereira, Carvalho, Mendes, Tavares, Correia, Pinto, Moreira, Lopes, Cardoso, Teixeira, Neves, Ramalho, Antunes, Fonseca',
  );
  addN(
    'NED',
    'Netherlands',
    '🇳🇱',
    'EUR',
    'Total-football passers',
    { passing: 2, vision: 1.5, technique: 1 },
    'Daan Sem Lars Bram Thijs Jesse Ruben Stijn Joris Milan Luuk Niels',
    'de Jong, Jansen, de Vries, van den Berg, Bakker, Visser, Smit, Meijer, de Boer, Mulder, Bos, Vos, Hendriks, Kuipers',
  );
  addN(
    'GER',
    'Germany',
    '🇩🇪',
    'EUR',
    'Disciplined and organised',
    { positioning: 1.5, workRate: 1.5, composure: 1.5 },
    'Lukas Leon Jonas Felix Maximilian Niklas Tim Jan Florian Moritz Julian Kai',
    'Schmidt, Schneider, Fischer, Weber, Wagner, Becker, Hoffmann, Koch, Richter, Klein, Wolf, Schröder, Neumann, Braun',
  );
  addN(
    'BEL',
    'Belgium',
    '🇧🇪',
    'EUR',
    'Golden-generation technicians',
    { technique: 1.5, vision: 1 },
    'Arne Wout Jens Thibault Lucas Mathis Siebe Senne Romain Jordan',
    'Peeters, Janssens, Maes, Jacobs, Willems, Claes, Goossens, Wouters, De Smet, Lambrecht, Verbeke, Michiels',
  );
  addN(
    'IRL',
    'Ireland',
    '🇮🇪',
    'ENG',
    'Committed and physical',
    { workRate: 2, strength: 1.5 },
    'Seán Conor Cian Darragh Oisín Ciarán Jamie Evan Adam Kevin Shane Ryan',
    "Murphy, Kelly, O'Brien, Byrne, O'Connor, Walsh, McCarthy, Gallagher, Kennedy, Brennan, Nolan, Duffy, Farrell, Quinn",
  );
  addN(
    'SCO',
    'Scotland',
    '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'ENG',
    'Tenacious competitors',
    { workRate: 2, tackling: 1 },
    'Callum Ross Euan Lewis Fraser Craig Scott Kyle Grant Stuart Jamie Liam',
    'MacDonald, Stewart, Anderson, Fraser, Reid, Ross, Murray, McKenzie, Paterson, Gillespie, Hamilton, Munro, Buchanan, Crawford',
  );
  addN(
    'WAL',
    'Wales',
    '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'ENG',
    'Hard-running and honest',
    { workRate: 1.5, stamina: 1 },
    'Rhys Dylan Gethin Owain Iwan Aled Cai Dafydd Tomos Rhodri',
    'Jones, Williams, Davies, Evans, Thomas, Roberts, Lewis, Morgan, Griffiths, Owen, Pugh, Llewellyn',
  );
  addN(
    'URU',
    'Uruguay',
    '🇺🇾',
    'SAM',
    'Garra charrúa — fierce defenders',
    { tackling: 2, composure: 1, strength: 1 },
    'Facundo Nahitan Maximiliano Agustín Brian Mathías Diego Sebastián Nicolás Gastón',
    'Olivera, Pereiro, Cabrera, Viñas, Silvera, Méndez, Acevedo, Laborda, Gutiérrez, Ferreira, Techera, Rolán',
  );
  addN(
    'COL',
    'Colombia',
    '🇨🇴',
    'SAM',
    'Rhythm and flair',
    { dribbling: 2, pace: 1.5 },
    'Andrés Carlos Jhon Santiago Camilo Daniel Jefferson Wilmar Stiven Kevin Yeison Duván',
    'Castaño, Borja, Arias, Palacios, Mosquera, Valencia, Cardona, Rentería, Quiñones, Hurtado, Guerrero, Murillo',
  );
  addN(
    'SEN',
    'Senegal',
    '🇸🇳',
    'AFR',
    'Powerful and quick',
    { pace: 2, strength: 2 },
    'Moussa Cheikh Pape Mamadou Ibrahima Abdou Youssouf Lamine Ousmane Aliou Babacar Modou',
    'Diop, Ndiaye, Fall, Cissé, Mbaye, Faye, Sow, Seck, Niang, Thiam, Badji, Ba',
  );
  addN(
    'GHA',
    'Ghana',
    '🇬🇭',
    'AFR',
    'Athletic and energetic',
    { pace: 2, strength: 1.5, workRate: 1 },
    'Kwame Kofi Yaw Kwabena Kwasi Samuel Emmanuel Isaac Joseph Abdul Richmond Kojo',
    'Mensah, Asante, Owusu, Appiah, Agyemang, Amoah, Adjei, Darko, Opoku, Ofori, Acheampong, Boakye',
  );
  addN(
    'CIV',
    'Ivory Coast',
    '🇨🇮',
    'AFR',
    'Explosive dribblers',
    { pace: 2, dribbling: 1.5, strength: 1 },
    'Yao Serge Jean Franck Ibrahim Seko Simon Evann Oumar Christian Arsène Hamed',
    'Koné, Kouassi, Bamba, Coulibaly, Ouattara, Diomandé, Kouamé, Doumbia, Gbamin, Konan, Yapi, Zoro',
  );
  addN(
    'MAR',
    'Morocco',
    '🇲🇦',
    'AFR',
    'Silky technicians',
    { technique: 2, dribbling: 1.5 },
    'Youssef Hamza Amine Ilias Soufiane Zakaria Anass Bilal Oussama Ayoub Nayef Adam',
    'El Amrani, Benali, Bennani, El Idrissi, Tazi, Alaoui, Berrada, Chakir, Lamrani, Haddadi, El Fassi, Ouazzani',
  );
  addN(
    'USA',
    'United States',
    '🇺🇸',
    'NAM',
    'Athletic, tireless',
    { stamina: 2, workRate: 1.5, pace: 1 },
    'Tyler Brandon Chris Josh Brenden Caleb Jordan Miles Gio Cole Austin Zack',
    'Johnson, Miller, Smith, Brown, Davis, Wilson, Moore, Taylor, Jackson, Harris, Clark, Parker, Reyes, Bennett',
  );
  addN(
    'DEN',
    'Denmark',
    '🇩🇰',
    'EUR',
    'Smart, composed',
    { positioning: 1.5, passing: 1, strength: 1 },
    'Mads Mikkel Rasmus Frederik Oliver Magnus Emil Jonas Kasper Mathias',
    'Nielsen, Jensen, Hansen, Pedersen, Larsen, Sørensen, Rasmussen, Poulsen, Madsen, Kristensen, Holm, Skov',
  );
  addN(
    'NOR',
    'Norway',
    '🇳🇴',
    'EUR',
    'Strong and durable',
    { strength: 1.5, stamina: 1.5, workRate: 1 },
    'Sander Martin Kristian Magnus Jonas Henrik Eirik Sindre Håkon Tobias Fredrik Ola',
    'Johansen, Olsen, Berg, Haugen, Dahl, Lund, Strand, Solberg, Bakken, Aas, Moen, Nygård',
  );
  addN(
    'CRO',
    'Croatia',
    '🇭🇷',
    'EUR',
    'Midfield masters',
    { technique: 1.5, vision: 1.5, composure: 1 },
    'Ivan Mateo Marko Josip Ante Nikola Dominik Filip Petar Mario Lovro Toma',
    'Horvat, Kovačević, Babić, Marić, Jurić, Knežević, Vuković, Perić, Pavić, Kolar, Božić, Grgić',
  );
  addN(
    'ITA',
    'Italy',
    '🇮🇹',
    'EUR',
    'Tactically astute defenders',
    { positioning: 2, tackling: 1.5, composure: 1 },
    'Lorenzo Matteo Alessandro Davide Andrea Riccardo Giacomo Simone Nicolò Gianluca Tommaso Edoardo',
    'Rossi, Russo, Ferrari, Esposito, Bianchi, Romano, Colombo, Ricci, Marino, Greco, Gallo, Conti',
  );

  FM.D.REGIONS = {
    ENG: 'British Isles',
    EUR: 'Europe',
    SAM: 'South America',
    NAM: 'North America',
    ASIA: 'Asia',
    AFR: 'Africa',
  };

  // Realistic nationality mix per league (weights ≈ % of squads) and per academy
  FM.D.NAT_MIX = {
    D1: {
      ENG: 38,
      FRA: 6,
      ESP: 5,
      POR: 5,
      BRA: 5,
      NED: 4,
      BEL: 3,
      GER: 3,
      ARG: 3,
      IRL: 3,
      SCO: 3,
      WAL: 2,
      NGA: 2,
      GHA: 2,
      SEN: 2,
      CIV: 2,
      DEN: 2,
      NOR: 2,
      JPN: 1.5,
      KOR: 1.5,
      USA: 1.5,
      URU: 1,
      COL: 1,
      MAR: 1,
      CRO: 1,
      SRB: 1,
      ITA: 1,
    },
    D2: {
      ENG: 60,
      IRL: 6,
      SCO: 5,
      WAL: 5,
      NED: 2,
      NGA: 2,
      GHA: 2,
      FRA: 2,
      DEN: 2,
      NOR: 2,
      USA: 2,
      JPN: 1,
      POR: 1,
      ESP: 1,
      BEL: 1,
      CIV: 1,
      SEN: 1,
      KOR: 1,
    },
    D3: { ENG: 72, IRL: 6, SCO: 6, WAL: 6, NGA: 2, GHA: 2, JPN: 1, USA: 1, NED: 1, DEN: 1, NOR: 1, FRA: 1 },
    ES2: { ESP: 76, ARG: 5, URU: 3, COL: 3, MAR: 3, BRA: 3, POR: 2, SEN: 1, FRA: 1, ITA: 1, SRB: 1, CRO: 1 },
    DE1: {
      GER: 52,
      FRA: 5,
      NED: 4,
      DEN: 3,
      NOR: 3,
      SRB: 3,
      CRO: 3,
      BRA: 3,
      JPN: 3,
      POR: 2,
      ESP: 2,
      KOR: 2,
      USA: 2,
      SEN: 2,
      CIV: 2,
      GHA: 2,
      ENG: 2,
      BEL: 2,
      ITA: 1,
      MAR: 1,
    },
    FR1: {
      FRA: 55,
      SEN: 5,
      CIV: 5,
      MAR: 4,
      BRA: 3,
      POR: 3,
      BEL: 3,
      ARG: 2,
      NGA: 2,
      GHA: 2,
      ESP: 2,
      NED: 1,
      GER: 1,
      CRO: 1,
      SRB: 1,
      JPN: 1,
      KOR: 1,
      USA: 1,
      URU: 1,
      COL: 1,
      ITA: 1,
    },
    BR1: { BRA: 86, ARG: 5, URU: 3, COL: 3, POR: 1, USA: 1, JPN: 1 },
    ES1: {
      ESP: 60,
      ARG: 6,
      BRA: 5,
      FRA: 4,
      URU: 3,
      POR: 3,
      COL: 3,
      MAR: 3,
      SEN: 1.5,
      NGA: 1,
      GER: 1,
      NED: 1,
      JPN: 1,
      KOR: 1,
      CRO: 1,
      SRB: 1,
      ITA: 1,
      ENG: 1,
      BEL: 1,
    },
  };
  FM.D.YOUTH_MIX = {
    ENG: { ENG: 84, IRL: 4, SCO: 3, WAL: 3, NGA: 1.5, GHA: 1.5, FRA: 1, POR: 1, JPN: 0.5, KOR: 0.5 },
    ESP: { ESP: 86, ARG: 3, MAR: 3, BRA: 2, COL: 2, URU: 1.5, POR: 1.5, SEN: 1 },
    GER: { GER: 88, CRO: 2, SRB: 2, GHA: 2, NED: 1, DEN: 1, USA: 1, KOR: 1, ITA: 1, FRA: 1 },
    FRA: { FRA: 82, SEN: 4, CIV: 4, MAR: 3, GHA: 2, POR: 2, BEL: 2, NGA: 1 },
    BRA: { BRA: 96, ARG: 2, URU: 1, COL: 1 },
  };

  // Hispanic naming uses two surnames when a combination is taken; others use a double-barrelled name
  FM.D.TWO_SURNAMES = ['ESP', 'ARG', 'URU', 'COL', 'POR', 'BRA'];

  FM.D.pickNat = (mix) => FM.U.wpick(Object.keys(mix), (k) => mix[k]);

  // Pre-season: friendlies and camps (3 pre-season slots)
  FM.D.CAMPS = {
    fitness: {
      name: 'Alpine fitness camp',
      icon: '🏔️',
      cost: 6e5,
      desc: 'Sharpens fitness and stamina. Everyone starts the season at 100%.',
    },
    tactical: {
      name: 'Tactical camp',
      icon: '🧠',
      cost: 4e5,
      desc: 'Drills your system. Big boost to tactical familiarity.',
    },
    youth: {
      name: 'Youth development camp',
      icon: '🌱',
      cost: 3e5,
      desc: 'Intensive coaching for players aged 21 and under.',
    },
    tour: {
      name: 'Commercial tour of Asia',
      icon: '✈️',
      cost: -2.5e6,
      desc: 'Earns money and new fans, but the travel tires the squad.',
    },
  };
  FM.D.PRESEASON_DAYS = 3;

  FM.D.STAFF_ROLES = {
    'Assistant Manager': { key: 'assistant', effect: 'Sharper advice on selection, tactics and the squad' },
    'First-Team Coach': { key: 'coach', effect: 'Faster player development' },
    'Head of Analytics': { key: 'analyst', effect: 'Moneyball insights and deeper post-match analysis' },
    'Head Physio': { key: 'physio', effect: 'Shorter injury layoffs' },
    'Sporting Director': { key: 'director', effect: 'Negotiates lower fees and wages' },
    Scout: { key: 'scout', effect: 'Finds and assesses players' },
  };

  // ---------- Club identities (drive board objectives + fan culture) ----------
  FM.D.IDENTITY = {
    oil: {
      label: 'Oil-Backed',
      icon: '🛢️',
      fans: 'Trophies. Nothing else matters.',
      budget: 2.0,
      sell: 1.6,
      obj: 'title',
    },
    giant: {
      label: 'Historic Giant',
      icon: '🏛️',
      fans: 'Expect to challenge for the title every season.',
      budget: 1.6,
      sell: 1.3,
      obj: 'top2',
    },
    historic: {
      label: 'Proud History',
      icon: '📜',
      fans: 'Want European nights and a top-half finish.',
      budget: 1.1,
      sell: 1.1,
      obj: 'tophalf',
    },
    fan: {
      label: 'Fan-Owned',
      icon: '🤝',
      fans: 'Demand attacking football and a club that lives within its means.',
      budget: 0.8,
      sell: 1.0,
      obj: 'attack',
    },
    youth: {
      label: 'Youth-Focused',
      icon: '🌱',
      fans: 'Love seeing academy kids get their chance.',
      budget: 0.8,
      sell: 1.0,
      obj: 'youth',
    },
    selling: {
      label: 'Selling Club',
      icon: '💼',
      fans: 'Accept sales — if you find the next gem.',
      budget: 0.9,
      sell: 0.85,
      obj: 'profit',
    },
    fallen: {
      label: 'Fallen Giant',
      icon: '🏚️',
      fans: 'Desperate for a return to former glory.',
      budget: 1.2,
      sell: 1.2,
      obj: 'rise',
    },
  };

  // National team kit colours
  FM.D.NT_COLORS = {
    ENG: ['#FFFFFF', '#CE1124'],
    BRA: ['#FFDF00', '#009C3B'],
    ARG: ['#75AADB', '#FFFFFF'],
    JPN: ['#1B2A6B', '#FFFFFF'],
    KOR: ['#C60C30', '#003478'],
    THA: ['#241D4F', '#A51931'],
    SRB: ['#C6363C', '#0C4076'],
    FRA: ['#002654', '#ED2939'],
    ESP: ['#AA151B', '#F1BF00'],
    NGA: ['#008751', '#FFFFFF'],
    POR: ['#8B0000', '#006600'],
    NED: ['#FF6600', '#FFFFFF'],
    GER: ['#FFFFFF', '#000000'],
    BEL: ['#E30613', '#000000'],
    IRL: ['#169B62', '#FFFFFF'],
    SCO: ['#0065BF', '#FFFFFF'],
    WAL: ['#C8102E', '#00B140'],
    URU: ['#5CBFEB', '#000000'],
    COL: ['#FCD116', '#003893'],
    SEN: ['#FFFFFF', '#00853F'],
    GHA: ['#FFFFFF', '#006B3F'],
    CIV: ['#F77F00', '#009E60'],
    MAR: ['#C1272D', '#006233'],
    USA: ['#FFFFFF', '#0A3161'],
    DEN: ['#C8102E', '#FFFFFF'],
    NOR: ['#BA0C2F', '#00205B'],
    CRO: ['#FF0000', '#FFFFFF'],
    ITA: ['#0066B3', '#FFFFFF'],
  };

  FM.D.CHANTS = [
    '"We\'re the pride of {city}, we\'ll never be moved!"',
    '"{short} till I die!"',
    '"Oh {city}, we love you!"',
    '"Glory, glory {nick}!"',
    '"Stand up for the {nick}!"',
  ];
  FM.D.TRADITIONS = [
    'Players walk out to a brass band',
    'Fans hold up scarves for the anthem before kick-off',
    'The home end sings through the whole 12th minute',
    "A minute's applause for every departing legend",
    'Tickets for kids cost £1 on derby day',
  ];

  // Staff
  FM.D.STAFF_PERSONALITY = ['Pragmatic', 'Old-School', 'Innovative', 'Outspoken', 'Loyal', 'Cautious', 'Ambitious'];

  FM.D.WEATHER = [
    ['Clear', '☀️', 0.55],
    ['Cloudy', '☁️', 0.2],
    ['Rain', '🌧️', 0.2],
    ['Snow', '❄️', 0.05],
  ];

  FM.D.SEASON_START = 2026;
  FM.D.WINDOW_ROUNDS = [0, 1, 2, 3, 11, 12, 13]; // transfer window open around these league rounds
  FM.D.YOUTH_ROUND = 16;
  // Calendar: cup days slot in after these league rounds (0-based)
  FM.D.CUP_AFTER = { 1: 'DC', 4: 'DC', 7: 'DC', 11: 'DC', 15: 'DC', 19: 'DC' }; // six rounds: 36 English clubs need a first round
  // Knockout stages are two-legged when the world rule is on (QF1/QF2, SF1/SF2); otherwise the "2" days are dropped
  FM.D.CC_AFTER = {
    2: 'G1',
    5: 'G2',
    8: 'G3',
    10: 'G4',
    13: 'G5',
    16: 'G6',
    17: 'QF1',
    18: 'QF2',
    19: 'SF1',
    20: 'SF2',
    21: 'F',
  };
  FM.D.CWC_AFTER = { 9: 'QF', 12: 'SF', 14: 'F' }; // Club World Cup, mid-season
  // Every international break has two matchdays
  FM.D.INTL_AFTER = { 7: ['I1a', 'I1b'], 15: ['I2a', 'I2b'] };
  // Wages were tuned against a 43-day season; longer calendars pay the same season total
  FM.D.WAGE_WEEKS = 43;

  // ---------- Alpha 1: Mexico ----------
  addN(
    'MEX',
    'Mexico',
    '🇲🇽',
    'NAM',
    'Quick, combative technicians',
    { technique: 1.5, pace: 1, workRate: 1 },
    'José Luis Carlos Juan Miguel Diego Jesús Héctor Andrés Edson Hirving Raúl Orbelín Uriel Alexis Santiago Érick César Julián Fernando Emilio Rodrigo Iván Gerardo Marco Víctor Omar Ángel',
    'Hernández, García, Martínez, López, González, Rodríguez, Sánchez, Ramírez, Cruz, Flores, Gómez, Morales, Vázquez, Reyes, Jiménez, Torres, Díaz, Gutiérrez, Ruiz, Mendoza, Aguilar, Ortiz, Castillo, Romero, Chávez, Rivera, Juárez, Domínguez, Vargas, Guzmán, Salazar, Esquivel, Orozco, Cervantes, Navarro, Montes',
  );
  FM.D.NT_COLORS.MEX = ['#006847', '#FFFFFF'];
  FM.D.TWO_SURNAMES.push('MEX');

  // ---------- More nations: the next European leagues by coefficient ----------
  addN(
    'TUR',
    'Turkey',
    '🇹🇷',
    'EUR',
    'Passionate, direct and aggressive',
    { workRate: 1.5, strength: 1, dribbling: 1 },
    'Emre Burak Mert Can Arda Kerem Oğuz Barış Cengiz Hakan Ozan Yusuf Berkay Serdar Umut Ömer Kaan Efe Alper Onur Tolga Cenk Volkan Egemen Selim Furkan Batuhan Enes Doğukan Halil Semih Kerim Ahmet Mehmet Ali Deniz Tuna Uğur Eren Irfan',
    'Yılmaz, Kaya, Demir, Şahin, Çelik, Yıldız, Yıldırım, Öztürk, Aydın, Özdemir, Arslan, Doğan, Kılıç, Aslan, Çetin, Kara, Koç, Kurt, Özkan, Şimşek, Polat, Korkmaz, Karaca, Erdem, Güneş, Aktaş, Bulut, Keskin, Ünal, Tekin, Akın, Uçar, Gül, Avcı, Taş, Sarı, Coşkun, Bozkurt, Kaplan, Özer, Tunç, Durmaz, Başaran, Karagöz, Ekici, Ateş, Işık, Soylu',
  );
  addN(
    'CZE',
    'Czechia',
    '🇨🇿',
    'EUR',
    'Industrious and well-drilled',
    { workRate: 1.5, positioning: 1, stamina: 1 },
    'Jan Jakub Tomáš Lukáš Ondřej Adam Matěj Filip Vojtěch David Petr Martin Michal Pavel Daniel Václav Josef Radim Tadeáš Šimon Dominik Marek Vladimír Antonín Štěpán Jiří Roman Aleš Libor Patrik Denis Robin Kryštof Vít Zdeněk Karel Hynek Mojmír Dalibor Bořek',
    'Novák, Svoboda, Novotný, Dvořák, Černý, Procházka, Kučera, Veselý, Horák, Němec, Pokorný, Marek, Pospíšil, Hájek, Jelínek, Král, Růžička, Beneš, Fiala, Sedláček, Doležal, Zeman, Kolář, Navrátil, Čermák, Urban, Vaněk, Blažek, Kříž, Kovář, Bartoš, Vlček, Polák, Musil, Kopecký, Šimek, Konečný, Malý, Holub, Štěpánek, Kadlec, Staněk, Soukup, Holý, Bureš, Jaroš, Richter, Moravec',
  );
  addN(
    'GRE',
    'Greece',
    '🇬🇷',
    'EUR',
    'Organised, resilient defenders',
    { positioning: 1.5, tackling: 1.5, strength: 1 },
    'Giorgos Dimitris Nikos Kostas Giannis Christos Vasilis Panagiotis Thanasis Michalis Stelios Sotiris Antonis Manolis Lefteris Apostolos Charalampos Konstantinos Alexandros Stavros Spyros Andreas Petros Pavlos Ilias Theodoros Fotis Marios Anastasios Evangelos Tasos Vangelis Lazaros Savvas Aris Achilleas Zisis Orestis Anestis Prodromos',
    'Papadopoulos, Papadakis, Georgiou, Oikonomou, Pappas, Vlachos, Nikolaidis, Dimitriou, Konstantinidis, Karagiannis, Athanasiou, Christodoulou, Ioannidis, Makris, Vasileiou, Antoniou, Papanikolaou, Alexiou, Stavrou, Kyriakidis, Theodorou, Michailidis, Economou, Lazaridis, Panagiotou, Spanos, Katsaros, Mavridis, Tsakalos, Zervas, Anagnostou, Sotiriou, Galanis, Petridis, Chatzis, Rigas, Voulgaris, Kontos, Tzavaras, Liakos, Marinos, Kalogeropoulos, Lamprou',
  );
  addN(
    'POL',
    'Poland',
    '🇵🇱',
    'EUR',
    'Strong, honest and direct',
    { strength: 1.5, workRate: 1.5, finishing: 1 },
    'Jakub Kacper Szymon Mateusz Bartosz Kamil Michał Paweł Piotr Krzysztof Tomasz Łukasz Dawid Adrian Marcin Patryk Damian Sebastian Przemysław Grzegorz Wojciech Maciej Filip Karol Hubert Oskar Igor Mikołaj Dominik Antoni Wiktor Jan Adam Konrad Rafał Arkadiusz Norbert Kornel Bartłomiej Radosław',
    'Nowak, Kowalski, Wiśniewski, Wójcik, Kowalczyk, Kamiński, Lewandowicz, Zieliński, Szymański, Woźniak, Dąbrowski, Kozłowski, Jankowski, Mazur, Kwiatkowski, Krawczyk, Kaczmarek, Piotrowski, Grabowski, Zając, Pawłowski, Michalski, Król, Wieczorek, Jabłoński, Wróbel, Nowakowski, Majewski, Olszewski, Stępień, Malinowski, Jaworski, Adamczyk, Dudek, Nowicki, Pawlak, Górski, Witkowski, Walczak, Sikora, Baran, Rutkowski, Michalak, Szewczyk, Ostrowski, Tomaszewski, Pietrzak, Duda',
  );
  addN(
    'AUT',
    'Austria',
    '🇦🇹',
    'EUR',
    'High-energy pressers',
    { workRate: 2, stamina: 1.5, pace: 0.5 },
    'Lukas David Florian Tobias Julian Stefan Christoph Dominik Philipp Matthias Andreas Michael Patrick Alexander Marco Kevin Fabian Maximilian Simon Sebastian Raphael Nicolas Konrad Leopold Valentin Moritz Jakob Elias Felix Samuel Benedikt Lorenz Clemens Paul Nico Marcel Manuel Thomas Georg Severin',
    'Gruber, Huber, Bauer, Wagner, Müller, Pichler, Steiner, Moser, Mayer, Hofer, Leitner, Berger, Fuchs, Eder, Fischer, Schmid, Winkler, Weber, Schwarz, Maier, Schneider, Reiter, Mayr, Schmidt, Wimmer, Egger, Brunner, Lang, Baumgartner, Auer, Binder, Lechner, Wolf, Wallner, Aigner, Ebner, Koller, Lehner, Haas, Schuster, Holzer, Kogler, Resch, Strasser, Pölzl, Grill, Posch, Seidl',
  );
  addN(
    'SUI',
    'Switzerland',
    '🇨🇭',
    'EUR',
    'Tidy, versatile and composed',
    { composure: 1.5, passing: 1, positioning: 1 },
    'Luca Noah Leon Nico Jan Fabian Kevin Yannick Cédric Florian Joël Silvan Remo Dario Marco Loris Nils Andrin Gian Ramon Mauro Samuel Timo Reto Beat Michel Simon Jonas Elias Lars Levin Aurèle Matteo Bastien Gaël Théo Kilian Ruben Dominik Pascal',
    'Müller, Meier, Schmid, Keller, Weber, Huber, Schneider, Meyer, Steiner, Fischer, Gerber, Brunner, Baumann, Frei, Zimmermann, Moser, Widmer, Wyss, Graf, Roth, Suter, Baumgartner, Kälin, Bühler, Aebischer, Zbinden, Marti, Lüthi, Gisler, Egli, Imhof, Studer, Ammann, Hofmann, Kunz, Blaser, Bachmann, Hess, Rossier, Favre, Perrin, Bonvin, Morand, Rochat, Chappuis, Bernasconi, Rossi, Bianchi',
  );
  Object.assign(FM.D.NT_COLORS, {
    TUR: ['#E30A17', '#FFFFFF'],
    CZE: ['#D7141A', '#11457E'],
    GRE: ['#0D5EAF', '#FFFFFF'],
    POL: ['#FFFFFF', '#DC143C'],
    AUT: ['#ED2939', '#FFFFFF'],
    SUI: ['#D52B1E', '#FFFFFF'],
  });
  // ---------- Bigger name pools: more combinations, fewer repeats across a 10,000-player world ----------
  // (unique-name enforcement in world.js). First names space-separated, surnames comma-separated.
  const MORE_NAMES = {
    ENG: [
      'William Henry Freddie Theo Max Louis Joshua Luca Toby Isaac Adam Elliot Harvey Finley Oscar Jacob Liam Zach Ashley Matt Josh Curtis Dominic Reuben Kian Leon Jayden Bailey Morgan Rory Scott Jake Sonny Rico Tobias Leo Bradley Craig Dean Ellis Gary Jason Kai Kieran Lee Neil Owen Paul Reggie Rob Sean Stuart Wes Ricky',
      'Robinson, Thompson, Lawrence, Chapman, Hodgson, Patterson, Whitaker, Ellis, Hartley, Newton, Burton, Sharp, Hayes, Cole, Fisher, Russell, Barker, Spencer, Webster, Atkinson, Holt, Parkes, Buckley, Mason, Nash, Gibbs, Porter, Reeve, Stone, Tate, Wheeler, Yates, Booth, Dixon, Frost, Hurst, Kirby, Lodge, Moss, Pearce, Rhodes, Shepherd, Summers, Watts, Addo, Asante, Okoye, Richards, Allen, Bailey, Baker, Bates, Bell, Bradley, Brooks, Collins, Cox, Dale, Dawson, Farrell, Ford, Foster, Graham, Grant, Hall, Harper, Hart, Hill, Holmes, Hunt, Hunter, Jennings, Kay, Kerr, Lane, Lawson, Lloyd, Miles, Nicholls, Norris, Parsons, Payne, Perry, Pope, Reid, Reynolds, Robson, Saunders, Simpson, Slater, Thornton, Tucker, Vaughan, Wade, Wells, Whitehead, Wilkinson, Woods',
    ],
    BRA: [
      'Gustavo Leonardo Guilherme Vitor Eduardo Marcelo Renan Danilo Paulo Anderson Douglas Fabrício Luan Murilo Otávio Raul Samuel Yuri Arthur Henrique Enzo Davi Heitor Bernardo Miguel Alisson Gérson Hugo Jean Kauã Marcos Nathan Rafinha Ronaldo Tales Wendel Yago Ygor Emerson Juninho Lucca Andrey Kaique',
      'Araújo, Cardoso, Martins, Freitas, Teixeira, Correia, Azevedo, Monteiro, Mendes, Batista, Cavalcanti, Duarte, Farias, Lacerda, Macedo, Nogueira, Peixoto, Queiroz, Siqueira, Vieira, Fonseca, Andrade, Castro, Cunha, Fernandes, Nunes, Pinto, Ramos, Reis, Rodrigues, Santana, Soares, Campos, Figueiredo, Lopes, Machado, Marques, Medeiros, Melo, Miranda, Moreira, Pires, Sales, Tavares',
    ],
    ARG: [
      'Ezequiel Leandro Joaquín Ramiro Maximiliano Bruno Thiago Alan Ignacio Federico Lucas Mateo Marcos Rodrigo Cristian Hernán Alejandro Carlos Damián Fernando Germán Guido Juan Luciano Martín Mauro Nahuel Pablo Axel Benjamín Bautista Brian Claudio Enzo Exequiel Gastón Jonathan Lisandro Milton Walter Luca',
      'Gómez, Pérez, Sánchez, Ramírez, Torres, Flores, Ruiz, Castro, Ortiz, Molina, Rojas, Vega, Giménez, Aguirre, Cabrera, Ledesma, Quiroga, Ponce, Villalba, Peralta, Godoy, Suárez, Silva, Morales, Núñez, Ríos, Ramos, Luna, Ferreyra, Paz, Juárez, Figueroa, Coronel, Arce, Bustos, Carrizo, Maidana, Ojeda, Páez, Rivero, Toledo, Vera, Zárate, Cáceres',
    ],
    JPN: [
      'Takuma Kazuki Ryota Naoki Shun Yusuke Kenji Tomoya Hayato Riku Sora Itsuki Kosuke Taichi Genki Shuto Asahi Daichi Eita Fumiya Hikaru Hinata Hiroto Jun Kazuya Keisuke Koki Kyosuke Makoto Masaki Minato Naoya Reo Ryusei Satoshi Shinji Shunsuke Soma Taiga Takeru Tatsuya Tomoki Tsubasa Wataru Yamato Yudai Yuma Yusei Akira Ayumu Haruki Issei Kento Rikuto Shinya',
      'Hayashi, Shimizu, Yamaguchi, Mori, Ikeda, Hashimoto, Ishikawa, Ogawa, Okada, Fujita, Goto, Kondo, Murakami, Nishimura, Sakamoto, Aoki, Fukuda, Maeda, Abe, Arai, Fujii, Hasegawa, Hirano, Honda, Ishii, Iwasaki, Kaneko, Kikuchi, Kinoshita, Kubo, Maruyama, Masuda, Matsuda, Miura, Miyazaki, Morita, Nakagawa, Nakano, Nakajima, Noguchi, Ota, Saito, Sakai, Sato, Shibata, Sugiyama, Takagi, Takeda, Tamura, Ueda, Uchida, Wada, Yamazaki, Yano, Yokoyama, Kojima, Hayashida, Nagai',
    ],
    KOR: [
      'Min-ho Hyun-woo Seung-min Jin-su Tae-yang Dong-won Kyung-ho Young-jae Sung-hoon Jun-seo Ha-neul Si-woo Chan-woo Dae-hyun Eun-su Gi-hyun Gyu-min Hae-won Ho-jun Hyeon-seok In-beom Ja-cheol Jae-sung Jeong-ho Ji-hwan Jin-woo Jong-hyun Joo-won Kyu-ri Min-jae Min-kyu Myung-jae Sang-min Se-hun Seok-ju Seung-ho Sung-min Tae-hwan Won-jun Woo-young Yeong-jae Yong-woo Young-min Hyung-min Chul-soo Kwang-hyun Jun-young',
      'Kwon, Song, Shin, Ahn, Seo, Moon, Bae, Baek, Nam, Ryu, Jeon, Hong, Hwang, Im, Heo, Yoo, Go, Yang, Son, Noh, Ha, Kwak, Sung, Cha, Joo, Woo, Min, Jin, Na, Ji, Um, Byun, Chae, Pyo, Gil, Ma, Do, Yeo, Ok, Seol',
    ],
    THA: [
      'Anon Apichat Chaiwat Jakkaphan Kittipong Nopphon Prasit Sittichok Thanakorn Wattana Yodsak Phakin Adisak Anucha Apisit Boonsong Chakrit Chalermchai Ekkachai Jirawat Kasem Kiattisak Korrawit Manop Nattawut Niran Panupong Pattara Phichit Pongsakorn Rattapong Sakda Somchai Sompong Sukree Surachet Tanaboon Teerasil Thitiphan Tossapol Umpol Vorawut Wanchai Wisarut Yutthana Charyl Poramet Kritsana',
      'Boonmee, Chaiyasit, Jaidee, Kongsri, Maneerat, Phromphan, Sukjai, Wongsawat, Yodchai, Pongsak, Sriwan, Thammarat, Anantasak, Buakhao, Chanthong, Charoensuk, Duangkaew, Intharat, Jantarasuk, Kaewkla, Khamsing, Lertsak, Meesuk, Nakprasert, Onsri, Panyasiri, Phetchara, Prasertsri, Ruangsri, Saelim, Sangthong, Siriwat, Somboon, Suwannarat, Tangsakul, Thongchai, Udomsak, Wattanachai, Wiriya, Yenphan, Kaewmanee, Boonkerd',
    ],
    SRB: [
      'Đorđe Milan Vladimir Bogdan Petar Dragan Ognjen Vuk Andrija Veljko Mihajlo Nenad Aleksa Andrej Bojan Branko Darko Dejan Dimitrije Goran Ivan Jovan Lazar Luka Marko Matija Miloš Mladen Nemanja Novak Pavle Radoš Relja Sava Srđan Stefan Uroš Vasilije Vukašin Zoran Željko Danilo Igor Ljubomir Mirko',
      'Popović, Živković, Janković, Radović, Obradović, Simić, Todorović, Vasić, Zdravković, Nedeljković, Filipović, Ristić, Aleksić, Antić, Bogdanović, Cvetković, Despotović, Đurić, Gajić, Jevtić, Krstić, Lazić, Maksimović, Mladenović, Novaković, Pantić, Perić, Radonjić, Rakić, Savić, Spasić, Stevanović, Stojković, Tomić, Veljković, Vukić, Zečević, Živanović, Jović, Marinković, Milovanović, Radenković',
    ],
    FRA: [
      'Louis Arthur Raphaël Tom Noah Adam Evan Axel Mathéo Baptiste Samuel Mamadou Adrien Benjamin Killian Wesley Alexis Aurélien Bastien Cédric Corentin Damien Dylan Florian Gaëtan Guillaume Jordan Julien Kévin Lenny Loïc Malo Marius Nicolas Olivier Quentin Rémi Romain Sacha Tanguy Valentin Victor Yann Youssouf Ismaël Kylian Warren Désiré Randal Eduardo Boubacar Souleymane Amadou',
      'Durand, Leroy, Roux, Fontaine, Chevalier, Robin, Garnier, Faure, Rousseau, Lemaire, Sylla, Sissoko, Cissé, Gomis, Picard, Gauthier, Bonnet, Lacroix, Barbier, Bertrand, Blanchard, Boyer, Brun, Caron, Clément, Colin, David, Denis, Dumont, Dupont, Fabre, Fournier, Gaillard, Guerin, Henry, Joly, Lambert, Lefèvre, Lemoine, Marchand, Masson, Mathieu, Meunier, Michel, Muller, Nicolas, Perrin, Petit, Renard, Richard, Rivière, Roussel, Roy, Simon, Thomas, Vidal, Kanté, Koné, Touré, Konaté, Doucouré, Sakho, Coulibaly, Keita',
    ],
    ESP: [
      'Carlos David Diego Jorge Raúl Víctor Alberto Fernando Luis Mario Óscar Alejandro Miguel Ángel Borja Gonzalo Nacho Unai Aitor Mikel Jon Asier Íñigo Gerard Pau Marc Jordi Eric Aleix Oriol Aarón Adrián Andrés Antonio Arnau Brais Cristian Enrique Ernesto Francisco Gerardo Guillermo Héctor Ismael Jaime José Juanma Julen Lucas Manuel Mateo Nico Rafa Ramón Rodrigo Samu Santi Tomás Xabi Yeray Ander Beñat Gorka Iñaki Joan Martí Pol Roger Xavi Hugo',
      'López, Pérez, González, Rodríguez, Fernández, Gómez, Díaz, Hernández, Álvarez, Jiménez, Romero, Alonso, Castro, Ortega, Rubio, Molina, Delgado, Suárez, Iglesias, Garrido, Cortés, Castillo, Santos, Lozano, Guerrero, Cano, Prieto, Méndez, Calvo, Gallego, Herrera, Peña, León, Márquez, Cabrera, Flores, Campos, Vega, Fuentes, Aguirre, Pascual, Blanco, Arias, Ibáñez, Lorente, Iturralde, Etxeberria, Zubiría, Aguilar, Bravo, Caballero, Cámara, Carmona, Crespo, Domínguez, Durán, Escudero, Esteban, Ferrer, Gallardo, Giménez, Guzmán, Hidalgo, Lara, Luque, Manzano, Marín, Mora, Nieto, Ortiz, Pastor, Quintero, Ramírez, Reyes, Robles, Rojas, Sáez, Salas, Sanz, Soler, Soto, Varela, Vázquez, Velasco, Zamora, Arrieta, Goikoetxea, Larrañaga',
    ],
    NGA: [
      'Chukwuemeka Obinna Olamide Femi Segun Yusuf Bright Frank Moses Kenneth Paul Sunday Abdullahi Akinwale Babatunde Chidera Chinedu Daniel David Ebuka Ejike Friday Godwin Ibrahim Innocent Jamiu Kingsley Kunle Michael Nnamdi Obafemi Oluwaseun Promise Raphael Rasheed Sadiq Seun Simeon Stanley Terem Tobi Umar Wale Yakubu Zaidu Calvin Cyriel Ademola Alhassan',
      'Ogbu, Ibe, Onyeka, Akinola, Okoro, Uzor, Bello, Lawal, Ajayi, Oladipo, Nnamdi, Afolabi, Abubakar, Adeleke, Afolayan, Agu, Aina, Akinyemi, Amadi, Anyanwu, Dike, Ekwueme, Ibekwe, Igwe, Kalu, Mohammed, Nwachukwu, Nwankwo, Obasi, Odion, Ogbonna, Okeke, Oyelaran, Sule, Umar, Yusuf, Ezenwa, Adeniyi, Chima, Emenike, Ogundipe, Olatunji, Onyeama, Uzoma, Babalola, Ezeh, Nnadi',
    ],
    POR: [
      'Bruno Rui Miguel Ricardo Luís Afonso Martim Tomás Alexandre Álvaro Artur Bernardo Carlos Daniel Duarte Eduardo Fábio Filipe Gabriel Henrique Hélder Ivo Joaquim Jorge Leonardo Lourenço Manuel Marco Mário Paulo Renato Rodrigo Salvador Samuel Sérgio Simão Tomé Vasco Xavier Gustavo Dinis Otávio',
      'Santos, Ferreira, Costa, Gomes, Martins, Rodrigues, Sousa, Oliveira, Ribeiro, Rocha, Matos, Barros, Almeida, Alves, Amaral, Andrade, Araújo, Azevedo, Batista, Borges, Brito, Campos, Castro, Cruz, Cunha, Dias, Esteves, Faria, Fernandes, Freitas, Guerreiro, Henriques, Leal, Leite, Loureiro, Macedo, Machado, Magalhães, Marques, Monteiro, Nogueira, Nunes, Pacheco, Paiva, Reis, Salgado, Seixas, Silva, Simões, Vaz, Vieira',
    ],
    NED: [
      'Tim Jasper Koen Tom Wout Sven Rick Kevin Dennis Jordy Bart Boy Calvin Cody Dirk Emil Gijs Hidde Jan Jens Jort Jurriën Kenneth Lucas Mats Max Micky Nathan Owen Pepijn Quinten Rens Robin Roel Ruud Sepp Sjoerd Teun Thom Tijjani Vincent Wessel Xavi Youri Zeno',
      'de Wit, Kramer, van Leeuwen, Dekker, Brouwer, Vermeulen, Willems, van der Meer, Prins, Postma, Boer, Bosch, van Dijk, van der Linden, Hoekstra, Huisman, Jacobs, de Graaf, de Groot, de Haan, de Koning, de Leeuw, Maas, Martens, Peters, Post, Scholten, Timmermans, van Beek, van Dam, van Dongen, van Loon, van Vliet, Verbeek, Verhoeven, Vink, Zwart, Koster, Evers, Brand, Veenstra, Wolters, Schouten',
    ],
    GER: [
      'Paul Lennard David Tobias Philipp Marco Luca Erik Noah Fabian Alexander Andreas Anton Ben Christian Daniel Dennis Dominik Elias Emil Finn Frederik Hannes Jakob Janik Johannes Jonathan Justin Karl Kevin Lars Lennart Linus Malte Mats Matthias Max Nils Ole Oskar Pascal Robin Sebastian Simon Stefan Thomas Timo Tom Vincent Yannick',
      'Zimmermann, Krüger, Hartmann, Lange, Schmitt, Meyer, Walter, König, Kaiser, Vogel, Peters, Frank, Albrecht, Arnold, Baumann, Beck, Böhm, Brandt, Busch, Dietrich, Engel, Friedrich, Fuchs, Graf, Günther, Haas, Hahn, Heinrich, Herrmann, Horn, Jung, Keller, Kraus, Kühn, Lehmann, Lorenz, Ludwig, Maier, Martin, Möller, Otto, Pohl, Roth, Sauer, Schäfer, Scholz, Schubert, Schulz, Schwarz, Seidel, Simon, Sommer, Stein, Thomas, Vogt, Werner, Winkler, Ziegler',
    ],
    BEL: [
      'Tibo Maxime Robbe Kobe Nathan Victor Brent Jelle Stef Lander Aster Bram Charles Cyriel Dante Dries Elias Emile Ferre Hugo Ilias Jarne Jonas Julien Kevin Leander Loïs Louis Mats Mauro Michiel Noah Olivier Pieter Quinten Rune Simon Tom Toon Warre Xander Yari Zeno Arthur Alexis',
      'Vermeersch, Declercq, Van Damme, Hermans, Aerts, Pauwels, Desmet, Vandenberghe, Coppens, Martens, Bogaert, Claeys, Cools, De Backer, De Clercq, De Cock, De Coster, Dewaele, De Wilde, Dubois, Dupont, Geerts, Hendrickx, Lemmens, Leroy, Lambert, Mertens, Moens, Nys, Segers, Simons, Smets, Stevens, Van Acker, Van den Broeck, Van Hoof, Vandamme, Verhaegen, Verstraete, Vervoort, Wuyts, Lefebvre, Mathieu',
    ],
    IRL: [
      'Aaron Dara Eoin Niall Liam Patrick Tadhg Ronan Cathal Fionn Adam Ben Bobby Callum Cillian Colm Conal Dáire Darren Declan Diarmuid Donal Eamon Fiachra Gavin James Jake John Kyle Luke Mark Mikey Odhran Padraig Peter Rian Rory Seamus Tiernan Tom Troy',
      'Lynch, Doherty, Moran, Hayes, Power, Reilly, Hogan, Kavanagh, Fitzgerald, Keane, Daly, Sheridan, Boyle, Brady, Burke, Carroll, Clarke, Coleman, Collins, Connolly, Cullen, Cunningham, Dempsey, Doyle, Dunne, Egan, Flanagan, Flynn, Foley, Gorman, Harrington, Healy, Hennessy, Horgan, Joyce, Keogh, Lawlor, Maguire, Mahon, McGrath, Molloy, Mulligan, Nugent, Regan, Ryan, Sweeney, Tierney, Whelan',
    ],
    SCO: [
      'Andrew Ryan Connor Jack Blair Calum Aidan Robbie Greg Dylan Aaron Alan Allan Barry Billy Brian Cammy Chris Colin Darren David Declan Gary Gordon Hamish Iain Jamie John Kenny Kevin Kieran Lawrence Lyall Malcolm Neil Rory Ruaridh Shaun Stephen Steven Stewart Tommy',
      'Thomson, Wilson, Scott, Cameron, Gordon, Kerr, Morrison, Duncan, Sinclair, Watson, Burns, Graham, Adam, Bain, Black, Brown, Campbell, Christie, Cooper, Dickson, Docherty, Donaldson, Ferguson, Forrest, Gray, Johnston, Kelly, Kennedy, Lawson, Mackay, Maclean, McLean, Miller, Mitchell, Taylor, Boyd, Craig, Dunlop, Fleming, Hay, Kirk, Lindsay, Ogilvie, Rennie, Wallace',
    ],
    WAL: [
      'Harry Joel Lewis Morgan Tom Elis Gareth Wyn Macsen Osian Aaron Ben Brennan Chris Connor Daniel David Ethan Gethin Harri Iolo Jac Jonny Jordan Kieffer Lloyd Mark Neco Nathan Rabbi Sion Sorba Wes Joe Ellis Rubin',
      'Rees, Phillips, Edwards, Parry, James, Powell, Hopkins, Bevan, Vaughan, Pritchard, Allen, Collins, Cooper, Davies, Hughes, Jenkins, King, Lawrence, Moore, Price, Roberts, Taylor, Thomas, Watkins, Wilson, Richards, Bowen, Howells, Jarvis, Lloyd, Meredith, Nash, Probert, Rowlands',
    ],
    URU: [
      'Martín Joaquín Rodrigo Mauricio Santiago Franco Emiliano Gonzalo Agustín Álvaro Bruno Carlos Cristian Damián Diego Felipe Fernando Gabriel Guillermo Ignacio Jonathan Juan Leonardo Lucas Luis Manuel Marcelo Nahuel Pablo Ronald Thiago Valentín Walter Alexis Christian Kevin Federico',
      'Pereira, Fernández, Martínez, Castro, Álvarez, Sosa, Benítez, Da Silva, Rivero, Correa, Acosta, Aguirre, Cáceres, Canobbio, Cardozo, Giménez, González, Hernández, López, Olivera, Rodríguez, Rosas, Sánchez, Silva, Torres, Varela, Viera, Villar, Zalazar, Bueno, Cabrera, Duarte, Etchegaray, Lemos, Machado, Nández, Pintos, Quintana',
    ],
    COL: [
      'Juan Sebastián Luis Felipe Alejandro Óscar Mateo Brayan Alexis Andrés Carlos Cristian Daniel David Deiver Diego Duván Edwin Eduardo Faustino Frank Gustavo Harold Jaminton Jhon Jhonatan Johan Jorge José Kevin Miguel Nicolás Richard Santiago Steven Wílmar Yerson',
      'Gómez, Hernández, Ramírez, Rojas, Ortiz, Moreno, Serna, Balanta, Cuesta, Perea, Barrios, Campaz, Carrascal, Castillo, Durán, Fabra, Guerrero, Hurtado, Lerma, Machado, Montero, Muñoz, Palacios, Quintero, Ríos, Rodríguez, Sánchez, Uribe, Valoy, Vargas, Arboleda, Bermúdez, Cárdenas, Escobar, Gaitán, Londoño, Mejía, Osorio, Restrepo, Zuluaga',
    ],
    SEN: [
      'Saliou Habib Assane Omar Malick Serigne Demba Khadim Abdoulaye Alioune Amadou Bamba Boulaye Cherif Dame Djibril Édouard El Hadji Fodé Formose Habibou Ismaïla Kalidou Krépin Lamine Mame Mbaye Moustapha Nampalys Nicolas Pathé Sadio Salif Samba Seydou Souleymane Youssouf Idrissa Iliman',
      'Dieng, Diatta, Diallo, Camara, Diédhiou, Mendy, Sy, Gning, Touré, Kouyaté, Baldé, Cissokho, Coly, Diagne, Diakhaby, Diarra, Diaw, Dieye, Diouf, Gassama, Gueye, Kanté, Keïta, Ndoye, Sabaly, Sall, Sané, Sène, Sidibé, Sonko, Tall, Wagué, Ndour, Ngom, Samb, Seye, Thiaw, Tine, Wade',
    ],
    GHA: [
      'Nana Kwaku Ebenezer Michael Daniel Prince Felix Collins Abdul Alexander Andrew Antoine Baba Benjamin Bernard Christopher Dennis Derrick Elisha Enoch Eric Ernest Evans Francis Frederick Gideon Ibrahim Inaki Jonathan Jordan Kamaldeen Kingsley Majeed Mohammed Mubarak Osman Patrick Razak Salis Thomas Tariq',
      'Kyei, Quaye, Tetteh, Nkrumah, Bonsu, Antwi, Sarpong, Yeboah, Owusu-Ansah, Donkor, Addo, Aidoo, Ampem, Annan, Asamoah, Badu, Bukari, Nuamah, Nyarko, Ofosu, Frimpong, Gyasi, Issahaku, Lamptey, Sulemana, Amankwah, Boahen, Dankwa, Fosu, Kusi, Manu, Nketiah, Obeng, Sarfo, Tawiah, Twumasi, Wiredu, Yamoah, Zakari',
    ],
    CIV: [
      'Wilfried Moussa Axel Nicolas Jérémie Kouadio Aboubacar Idriss Abdoul Adama Alain Amad Arthur Bakary Christian Didier Emmanuel Éric Evann Franck Gervais Guéla Hamed Ibrahim Jean-Michaël Jonathan Karim Lassina Maxwel Odilon Oumar Salomon Sébastien Sékou Simon Willy Yaya',
      "Traoré, Cissé, Diaby, Sangaré, Tiéné, Akpa, Seri, Kanga, Boli, Gradel, Adingra, Aké, Boga, Deli, Diakité, Fofana, Konan, Kouamé, Ouattara, Singo, Soumahoro, Touré, Yao, Agba, Assi, Beugré, Dago, Ehui, Gnahoré, Kacou, Loba, N'Guessan, Tanoh, Yeboué, Zadi",
    ],
    MAR: [
      'Mehdi Karim Rayane Omar Reda Nabil Walid Taha Abdelhamid Abderrazak Achraf Adil Ahmed Anas Azzedine Brahim Chadi Driss Eliesse Hakim Ibrahim Imran Ismael Jawad Khalid Mounir Mohamed Munir Nordin Noussair Othmane Rachid Romain Sofiane Selim Yahia Yassine Younes Zakaria',
      'Ziani, Kaddouri, Mansouri, Benjelloun, Tahiri, Chraibi, Rachidi, Slimani, Bouzidi, Naciri, Aboukhlal, Adli, Attiat-Allah, Chair, Dari, El Khannouss, El Yamiq, Ezzalzouli, Ouahabi, Rahimi, Sabiri, Zaroury, Belhanda, Fajr, Louza, Amrani, Bakkali, Cherkaoui, El Ouardi, Fikri, Hamdaoui, Jabri, Kharbouch, Mouline, Nejjari, Sefrioui, Tounsi, Zeroual',
    ],
    USA: [
      'Ryan Kyle Matt Nick Tanner Hunter Jesse Diego Aidan Luke Alex Andrew Anthony Benjamin Blake Brian Cameron Carter Chase Christian Clint Daniel DeAndre Dylan Eric Ethan Gabriel Jacob Jalen Jonathan Joshua Julian Justin Landon Logan Malik Mark Owen Paxten Reggie Ricardo Sergiño Timothy Walker Weston Yunus',
      'Thomas, White, Lopez, Walker, Young, King, Wright, Scott, Green, Carter, Mitchell, Rivera, Anderson, Cannon, Evans, Ferreira, Hall, Horvath, Lewis, Long, Martinez, Morris, Nelson, Robinson, Scally, Turner, Zimmerman, Barnes, Cooper, Brooks, Campbell, Collins, Edwards, Fisher, Graham, Hughes, Kelly, Murphy, Perez, Ross, Sanders, Stewart, Ward, Wood',
    ],
    DEN: [
      'Christian Viktor Anders Nicolai Rune Jeppe Victor Tobias Alexander Andreas Casper Daniel Elias Gustav Jacob Jens Joakim Jonas Kristoffer Lasse Lucas Malthe Marcus Martin Morten Nikolaj Oliver Pierre-Emile Rasmus Sebastian Simon Thomas Troels William Yussuf Asger Silas Mathias',
      'Thomsen, Mortensen, Jørgensen, Knudsen, Lauridsen, Dalsgaard, Bech, Vestergaard, Friis, Bruun, Andersen, Christensen, Damsgaard, Frandsen, Gregersen, Isaksen, Jakobsen, Kristiansen, Lindstrøm, Olesen, Stryger, Winther, Østergaard, Hermansen, Mikkelsen, Bang, Dam, Enevoldsen, Fog, Gade, Holst, Juhl, Krogh, Lund, Mogensen, Nørregaard, Overgaard, Riis, Schou, Thygesen',
    ],
    NOR: [
      'Ole Stian Even Mats Aksel Vegard Jørgen Petter Alexander Andreas Anders Birger Bjørn Daniel Erling Fredrik Gustav Hans Harald Jens Jo Johannes Julian Kasper Kristoffer Leo Lars Marius Martin Morten Oscar Patrick Per Sebastian Sondre Stefan Thomas Tor Torbjørn Vetle',
      'Nilsen, Pettersen, Karlsen, Kristiansen, Jacobsen, Halvorsen, Eide, Thorsen, Brekke, Myhre, Aasgaard, Ajer, Berge, Bjørkan, Hanche-Olsen, Hauge, Holm, Jensen, Larsen, Meling, Nyland, Pedersen, Selvik, Solbakken, Strandberg, Thorsby, Tangvik, Skaug, Eggen, Aune, Bakke, Brenden, Fjeld, Grønli, Hovland, Lie, Ness, Rønning, Sæther, Tveit',
    ],
    CRO: [
      'Borna Duje Joško Stipe Tin Kristijan Matej Ante Andrej Antonio Bruno Damir Darko Dario Davor Domagoj Hrvoje Igor Ivo Josip Lovro Luka Marin Martin Mateo Matija Mislav Niko Nikola Robert Roko Stjepan Tomislav Vedran Zvonimir Petar',
      'Šimić, Radić, Lovrić, Petković, Barić, Matić, Galić, Bašić, Rukavina, Jelić, Blažević, Bošnjak, Brajković, Bralić, Crnković, Čović, Dragić, Filipović, Galović, Grubišić, Herceg, Ivanković, Jakovljević, Jukić, Katić, Klarić, Kovač, Lončar, Lukić, Mikulić, Novak, Pavlović, Perković, Polić, Radošević, Sertić, Šarić, Tomić, Vidović, Vrdoljak, Zovko',
    ],
    ITA: [
      'Marco Luca Francesco Stefano Pietro Filippo Emanuele Manuel Leonardo Giorgio Alberto Alessio Antonio Carlo Claudio Cristiano Daniele Diego Enrico Fabio Federico Gabriele Gaetano Giovanni Giuseppe Jacopo Luigi Mattia Michele Mirko Nicola Paolo Raffaele Roberto Salvatore Samuele Sandro Tommaso Umberto Valerio Vincenzo Christian Destiny',
      "Costa, Fontana, Moretti, Barbieri, Lombardi, Rinaldi, Caruso, Ferri, Galli, Martini, Leone, Longo, Gentile, Villa, Amato, Barone, Basile, Benedetti, Bernardi, Bruno, Cattaneo, Coppola, D'Angelo, De Luca, De Rosa, Farina, Fiore, Giordano, Grasso, Guerra, Mancini, Mariani, Marchetti, Messina, Monti, Morelli, Neri, Orlando, Palumbo, Parisi, Pellegrini, Riva, Rizzo, Ruggiero, Sala, Santoro, Serra, Silvestri, Testa, Valentini, Vitale",
    ],
    MEX: [
      'Adrián Alan Alejandro Armando Brian César Christian Daniel Eduardo Efraín Emmanuel Érick Fidel Gilberto Guillermo Hugo Isaac Israel Jesús Jonathan Jorge Kevin Luis Manuel Mario Osvaldo Pablo Rogelio Sebastián Tomás Ulises',
      'Aguirre, Arteaga, Ayala, Beltrán, Cabrera, Campos, Delgado, Espinoza, Estrada, Fuentes, Galindo, Herrera, Lara, Leyva, Lozano, Macías, Medina, Montes, Navarro, Ochoa, Pérez, Quiñones, Ramos, Ríos, Rosales, Salcedo, Sandoval, Tapia, Valdez, Vega, Zavala',
    ],
  };
  for (const code in MORE_NAMES) FM.D.addNames(code, ...MORE_NAMES[code]);

  // Every league, data-driven, at its real size. repBand = the reputation range a league's clubs drift toward.
  // rules.rounds caps the fixture list where the real format isn't a full double round-robin (MLS: 34 games; Argentina: one round-robin).
  // Continental places: Europe 16 (ENG/ESP/GER/ITA 3, FRA 2, POR 1, NED 1); South America 8; Asia, Africa, North America 8 each.
  FM.D.LEAGUES = [
    {
      id: 'D1',
      nat: 'ENG',
      name: 'Premier League',
      short: 'PL',
      tier: 1,
      sim: 'full',
      clubs: 'CLUBS_D1',
      repBand: [88, 61],
      rules: { relegate: { to: 'D2', n: 3 }, qualify: { to: 'CC', n: 3 } },
    },
    {
      id: 'D2',
      nat: 'ENG',
      name: 'EFL Championship',
      short: 'CH',
      tier: 2,
      sim: 'full',
      clubs: 'CLUBS_D2',
      repBand: [61, 47],
      rules: { promote: { to: 'D1', auto: 2, playoff: [3, 6] }, relegate: { to: 'D3', n: 3 } },
    },
    {
      id: 'D3',
      nat: 'ENG',
      name: 'EFL League One',
      short: 'LO',
      tier: 3,
      sim: 'light',
      clubs: 'CLUBS_D3',
      repBand: [49, 39],
      rules: { promote: { to: 'D2', auto: 2, playoff: [3, 6] } },
    },
    {
      id: 'ES1',
      nat: 'ESP',
      name: 'LaLiga',
      short: 'LL',
      tier: 1,
      sim: 'full',
      clubs: 'CLUBS_ES1',
      repBand: [89, 58],
      rules: { relegate: { to: 'ES2', n: 3 }, qualify: { to: 'CC', n: 3 } },
    },
    {
      id: 'ES2',
      nat: 'ESP',
      name: 'Segunda División',
      short: 'SD',
      tier: 2,
      sim: 'light',
      clubs: 'CLUBS_ES2',
      repBand: [56, 45],
      rules: { promote: { to: 'ES1', auto: 2, playoff: [3, 6] } },
    },
    {
      id: 'DE1',
      nat: 'GER',
      name: 'Bundesliga',
      short: 'BL',
      tier: 1,
      sim: 'full',
      clubs: 'CLUBS_DE1',
      repBand: [89, 58],
      rules: { qualify: { to: 'CC', n: 3 } },
    },
    {
      id: 'FR1',
      nat: 'FRA',
      name: 'Ligue 1',
      short: 'L1',
      tier: 1,
      sim: 'full',
      clubs: 'CLUBS_FR1',
      repBand: [90, 57],
      rules: { qualify: { to: 'CC', n: 2 } },
    },
    {
      id: 'BR1',
      nat: 'BRA',
      name: 'Brasileirão Série A',
      short: 'BSA',
      tier: 1,
      sim: 'full',
      clubs: 'CLUBS_BR1',
      repBand: [85, 62],
      rules: { qualify: { to: 'CL', n: 5 } },
    },
    {
      id: 'IT1',
      nat: 'ITA',
      name: 'Serie A',
      short: 'SA',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_IT1',
      repBand: [86, 58],
      rules: { qualify: { to: 'CC', n: 3 } },
    },
    {
      id: 'PT1',
      nat: 'POR',
      name: 'Primeira Liga',
      short: 'PRL',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_PT1',
      repBand: [83, 53],
      rules: { qualify: { to: 'CC', n: 1 } },
    },
    {
      id: 'NL1',
      nat: 'NED',
      name: 'Eredivisie',
      short: 'ERE',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_NL1',
      repBand: [81, 54],
      rules: { qualify: { to: 'CC', n: 1 } },
    },
    {
      id: 'AR1',
      nat: 'ARG',
      name: 'Liga Profesional',
      short: 'LPF',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_AR1',
      repBand: [79, 53],
      rules: { rounds: 27, qualify: { to: 'CL', n: 3 } },
    },
    {
      id: 'US1',
      nat: 'USA',
      name: 'Major League Soccer',
      short: 'MLS',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_US1',
      repBand: [67, 55],
      rules: { rounds: 34, qualify: { to: 'NC', n: 4 } },
    },
    {
      id: 'JP1',
      nat: 'JPN',
      name: 'J1 League',
      short: 'J1',
      tier: 1,
      sim: 'light',
      clubs: 'CLUBS_JP1',
      repBand: [64, 53],
      rules: { qualify: { to: 'AC', n: 4 } },
    },
    {
      id: 'MX1',
      nat: 'MEX',
      name: 'Liga MX',
      short: 'LMX',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_MX1',
      repBand: [70, 55],
      rules: { qualify: { to: 'NC', n: 4 } },
    },
    {
      id: 'KR1',
      nat: 'KOR',
      name: 'K League 1',
      short: 'K1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_KR1',
      repBand: [60, 51],
      rules: { qualify: { to: 'AC', n: 2 } },
    },
    {
      id: 'TH1',
      nat: 'THA',
      name: 'Thai League 1',
      short: 'T1',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_TH1',
      repBand: [56, 44],
      rules: { qualify: { to: 'AC', n: 2 } },
    },
    {
      id: 'NG1',
      nat: 'NGA',
      name: 'Nigeria Premier Football League',
      short: 'NPFL',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_NG1',
      repBand: [55, 45],
      rules: { qualify: { to: 'AF', n: 4 } },
    },
    {
      id: 'MA1',
      nat: 'MAR',
      name: 'Botola Pro',
      short: 'BP',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_MA1',
      repBand: [59, 46],
      rules: { qualify: { to: 'AF', n: 4 } },
    },
    {
      id: 'RS1',
      nat: 'SRB',
      name: 'Serbian SuperLiga',
      short: 'SSL',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_RS1',
      repBand: [64, 46],
      rules: {},
    },
    {
      id: 'BE1',
      nat: 'BEL',
      name: 'Belgian Pro League',
      short: 'JPL',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_BE1',
      repBand: [68, 50],
      rules: {},
    },
    {
      id: 'TR1',
      nat: 'TUR',
      name: 'Süper Lig',
      short: 'SL',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_TR1',
      repBand: [72, 50],
      rules: {},
    },
    {
      id: 'CZ1',
      nat: 'CZE',
      name: 'Czech First League',
      short: 'CFL',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_CZ1',
      repBand: [64, 46],
      rules: {},
    },
    {
      id: 'GR1',
      nat: 'GRE',
      name: 'Super League Greece',
      short: 'SLG',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_GR1',
      repBand: [68, 48],
      rules: {},
    },
    {
      id: 'NO1',
      nat: 'NOR',
      name: 'Eliteserien',
      short: 'ES',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_NO1',
      repBand: [63, 46],
      rules: {},
    },
    {
      id: 'PL1',
      nat: 'POL',
      name: 'Ekstraklasa',
      short: 'EKS',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_PL1',
      repBand: [62, 46],
      rules: {},
    },
    {
      id: 'DK1',
      nat: 'DEN',
      name: 'Danish Superliga',
      short: 'DSL',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_DK1',
      repBand: [64, 48],
      rules: {},
    },
    {
      id: 'AT1',
      nat: 'AUT',
      name: 'Austrian Bundesliga',
      short: 'ABL',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_AT1',
      repBand: [64, 46],
      rules: {},
    },
    {
      id: 'CH1',
      nat: 'SUI',
      name: 'Swiss Super League',
      short: 'SSL2',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_CH1',
      repBand: [63, 48],
      rules: {},
    },
    {
      id: 'SC1',
      nat: 'SCO',
      name: 'Scottish Premiership',
      short: 'SPFL',
      tier: 1,
      sim: 'minimal',
      clubs: 'CLUBS_SC1',
      repBand: [70, 46],
      rules: {},
    },
  ];
  FM.D.CONTINENTALS = [
    { id: 'CC', region: 'Europe', name: 'UEFA Champions League', short: 'UCL', prize: 15e6 },
    { id: 'CL', region: 'South America', name: 'Copa Libertadores', short: 'LIB', prize: 8e6 },
    { id: 'AC', region: 'Asia', name: 'AFC Champions League Elite', short: 'ACLE', prize: 5e6 },
    { id: 'AF', region: 'Africa', name: 'CAF Champions League', short: 'CAF', prize: 3e6 },
    { id: 'NC', region: 'North America', name: 'CONCACAF Champions Cup', short: 'CCC', prize: 4e6 },
  ];
  // Club World Cup: last season's continental finalists (winners only from Africa and North America)
  // [competition, 0 = winner / 1 = runner-up], in seed order
  FM.D.CWC_SEEDS = [
    ['CC', 0],
    ['CL', 0],
    ['CC', 1],
    ['CL', 1],
    ['AC', 0],
    ['AF', 0],
    ['NC', 0],
    ['AC', 1],
  ];
  // Squad sizes per tier (+ academy prospects)
  FM.D.SQUAD_TIER = {
    // deep enough to cover injuries, suspensions and rotation (full: 26 senior players, three of them keepers)
    full: { GK: 3, CB: 5, FB: 4, DM: 2, CM: 4, AM: 2, W: 4, ST: 2 },
    light: { GK: 2, CB: 3, FB: 3, DM: 2, CM: 3, AM: 2, W: 3, ST: 2 },
    minimal: { GK: 2, CB: 3, FB: 2, DM: 1, CM: 2, AM: 1, W: 2, ST: 2 },
  };
  FM.D.ACADEMY_TIER = { full: 2, light: 2, minimal: 1 };

  // Nationality mixes for the new leagues
  Object.assign(FM.D.NAT_MIX, {
    IT1: {
      ITA: 58,
      ARG: 4,
      BRA: 4,
      FRA: 4,
      SRB: 3,
      CRO: 3,
      NED: 2,
      POR: 2,
      ESP: 2,
      DEN: 2,
      NOR: 2,
      SEN: 2,
      NGA: 2,
      MAR: 2,
      URU: 2,
      COL: 2,
      GER: 2,
      BEL: 2,
    },
    NL1: {
      NED: 64,
      BEL: 6,
      MAR: 4,
      DEN: 3,
      NOR: 3,
      GHA: 2,
      NGA: 2,
      SEN: 2,
      BRA: 2,
      SRB: 2,
      CRO: 2,
      JPN: 2,
      GER: 2,
      KOR: 1,
      USA: 1,
      POR: 1,
    },
    PT1: {
      POR: 55,
      BRA: 18,
      ARG: 4,
      URU: 3,
      COL: 3,
      ESP: 3,
      SEN: 2,
      CIV: 2,
      NGA: 2,
      FRA: 2,
      MAR: 2,
      GHA: 2,
      SRB: 1,
      JPN: 1,
    },
    AR1: { ARG: 88, URU: 5, COL: 4, BRA: 1, USA: 1, ESP: 1 },
    US1: {
      USA: 60,
      MEX: 8,
      COL: 4,
      ARG: 4,
      ENG: 3,
      GHA: 3,
      NGA: 2,
      JPN: 2,
      KOR: 2,
      BRA: 2,
      URU: 2,
      FRA: 2,
      GER: 2,
      ESP: 2,
      SCO: 1,
      IRL: 1,
    },
    JP1: { JPN: 88, KOR: 5, BRA: 4, THA: 2, SRB: 1 },
    MX1: { MEX: 70, ARG: 8, COL: 6, URU: 5, USA: 4, BRA: 3, ESP: 2 },
    NG1: { NGA: 95, GHA: 3, CIV: 1, SEN: 1 },
    KR1: { KOR: 88, BRA: 6, JPN: 3, SRB: 1, USA: 1 },
    TH1: { THA: 80, BRA: 7, JPN: 5, KOR: 5, SRB: 2, NGA: 1 },
    RS1: { SRB: 80, CRO: 4, GHA: 3, NGA: 3, BRA: 3, MAR: 2, SEN: 2, JPN: 1 },
    MA1: { MAR: 88, SEN: 4, CIV: 3, GHA: 2, NGA: 2, FRA: 1 },
  });

  Object.assign(FM.D.NAT_MIX, {
    BE1: {
      BEL: 60,
      NED: 6,
      FRA: 5,
      SEN: 3,
      CIV: 3,
      GHA: 3,
      NGA: 3,
      MAR: 3,
      DEN: 2,
      NOR: 2,
      JPN: 2,
      COL: 2,
      BRA: 2,
      CRO: 2,
      SRB: 2,
    },
    TR1: {
      TUR: 62,
      BRA: 4,
      NGA: 3,
      SEN: 3,
      CIV: 2,
      GHA: 2,
      POR: 3,
      NED: 2,
      SRB: 2,
      CRO: 2,
      ARG: 2,
      COL: 2,
      FRA: 2,
      GER: 2,
      MAR: 2,
      POL: 2,
      CZE: 1,
      GRE: 1,
      BEL: 1,
    },
    CZ1: { CZE: 80, POL: 3, SRB: 2, CRO: 2, NGA: 2, GHA: 2, AUT: 2, GER: 1, SEN: 2, CIV: 2, BRA: 1, TUR: 1 },
    GR1: {
      GRE: 58,
      SRB: 4,
      POR: 4,
      BRA: 4,
      ARG: 3,
      ESP: 3,
      CRO: 3,
      NGA: 2,
      SEN: 2,
      CIV: 2,
      NED: 2,
      POL: 2,
      MAR: 2,
      FRA: 2,
      COL: 2,
      URU: 2,
      CZE: 1,
      TUR: 1,
    },
    NO1: { NOR: 80, DEN: 4, GHA: 3, NGA: 3, SEN: 2, USA: 2, CIV: 2, NED: 1, BEL: 1, POL: 1, SUI: 1 },
    PL1: {
      POL: 70,
      CZE: 3,
      SRB: 3,
      CRO: 3,
      POR: 3,
      ESP: 3,
      BRA: 2,
      NGA: 2,
      GHA: 2,
      SEN: 2,
      NOR: 1,
      DEN: 1,
      GRE: 1,
      AUT: 1,
      TUR: 1,
      NED: 1,
      GER: 1,
    },
    DK1: {
      DEN: 74,
      NOR: 4,
      NGA: 3,
      GHA: 3,
      SEN: 2,
      NED: 2,
      BEL: 2,
      USA: 2,
      CIV: 2,
      JPN: 1,
      KOR: 1,
      SUI: 1,
      POL: 1,
      AUT: 1,
      CZE: 1,
    },
    AT1: {
      AUT: 64,
      GER: 8,
      SUI: 3,
      CRO: 3,
      SRB: 2,
      CZE: 2,
      POL: 2,
      NGA: 2,
      GHA: 2,
      CIV: 2,
      SEN: 2,
      MAR: 2,
      BRA: 2,
      JPN: 2,
      KOR: 2,
      DEN: 1,
      NOR: 1,
    },
    CH1: {
      SUI: 62,
      FRA: 6,
      GER: 4,
      ITA: 4,
      AUT: 3,
      CRO: 2,
      SRB: 2,
      POR: 2,
      SEN: 2,
      CIV: 2,
      GHA: 2,
      NGA: 2,
      BRA: 2,
      COL: 2,
      CZE: 1,
      POL: 1,
      TUR: 1,
    },
    SC1: {
      SCO: 58,
      ENG: 12,
      IRL: 6,
      WAL: 2,
      JPN: 3,
      KOR: 2,
      NOR: 2,
      DEN: 2,
      NED: 2,
      BEL: 1,
      NGA: 2,
      GHA: 2,
      USA: 2,
      CIV: 1,
      CRO: 1,
      POL: 1,
    },
  });

  // ---------- Alpha 1: contracts, agents, promises, badges ----------
  FM.D.AGENTS = {
    Shark: {
      icon: '🦈',
      desc: 'Squeezes every dollar. Walks away quickly.',
      demand: 1.12,
      patience: 2,
      fee: 0.08,
      bonusW: 1,
    },
    Pragmatic: { icon: '🤝', desc: 'Reasonable, wants a fair deal.', demand: 1.0, patience: 4, fee: 0.05, bonusW: 1 },
    Family: {
      icon: '🏡',
      desc: 'A relative looking after him. Values security and long deals.',
      demand: 0.95,
      patience: 5,
      fee: 0.03,
      bonusW: 0.9,
      longDeal: true,
    },
    Showman: {
      icon: '🎤',
      desc: 'Loves a headline number — big signing bonuses.',
      demand: 1.04,
      patience: 3,
      fee: 0.06,
      bonusW: 1.6,
    },
    Rookie: {
      icon: '🧢',
      desc: 'New to the game. Easy to deal with.',
      demand: 0.92,
      patience: 5,
      fee: 0.03,
      bonusW: 1,
    },
  };
  FM.D.AGENT_FIRMS = [
    'Apex Sports',
    'Stellar Group',
    'Blue Line Mgmt',
    'Goldfoot Agency',
    'Pinnacle Talent',
    'Northstar Football',
    'Premier Reps',
    'Crest & Co.',
    'Touchline Talent',
    'Wembley Mgmt',
  ];
  // Squad status: promised starts per season share, and what players expect relative to the squad
  FM.D.STATUS = {
    key: { label: 'Key player', share: 0.75, apps: 38 },
    regular: { label: 'Regular starter', share: 0.55, apps: 30 },
    rotation: { label: 'Rotation', share: 0.3, apps: 18 },
    backup: { label: 'Backup', share: 0.1, apps: 8 },
    prospect: { label: 'Prospect', share: 0.05, apps: 4 },
  };
  FM.D.BADGES = ['National C', 'Continental B', 'Continental A', 'Continental Pro'];
  FM.D.BADGE_COURSE = {
    'Continental A': { cost: 6e4, days: 12, rep: 3 },
    'Continental Pro': { cost: 1.5e5, days: 18, rep: 5 },
  };
})();
